theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - attr_list
    - md_in_html
    - navigation.top
    - header.autohide
  palette:
    primary: black
    accent: indigo
  logo:
repo_url: https://github.com/theogonic/cronus
site_name: Cronus
nav:
  - Home: index.md
  - Generators:
    - rust: generators/rust.md
    - rust-axum: generators/rust_axum.md
    - typescript: generators/ts.md
    - ts-nestjs: generators/ts_nestjs.md
    - openapi: generators/openapi.md
  - References:
    - YAML Format: references/yaml.md
    - API Format: references/api.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences