[package]
name = "cronus_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
cronus_generator = { path = "../../lib/generator" }
cronus_parser = { path = "../../lib/parser" }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"